// Plain-English definitions for each hazard category.
//
// These are static reference copy — the same definition is shown for
// every volcano. Per-volcano risk level and a one-line "why this
// volcano" note come from the volcano's `hazardRisks` record in
// volcano-history.ts.
//
// Sources:
// - USGS Volcano Hazards Program plain-language explainers
// - Smithsonian GVP "Hazards" glossary
// - Sigurdsson et al., Encyclopedia of Volcanoes (2nd ed., 2015)

import type { HazardCategory } from "../volcano-history";

export interface HazardDefinition {
  label: string; // short display label
  definition: string; // 1–2 sentence plain-English explainer
}

export const HAZARD_DEFINITIONS: Record<HazardCategory, HazardDefinition> = {
  pyroclastic: {
    label: "Pyroclastic flow",
    definition:
      "A ground-hugging cloud of hot ash, gas, and rock that moves downhill at 100+ km/h and is hot enough to kill on contact. Almost nothing in its path survives.",
  },
  ashfall: {
    label: "Ashfall",
    definition:
      "Fine rock and glass particles raining down from an eruption column. Just a few centimeters can collapse roofs, short-circuit power grids, contaminate water, and ground aircraft hundreds of kilometers away.",
  },
  lahar: {
    label: "Lahar",
    definition:
      "A fast-moving volcanic mudflow — the consistency of wet concrete — triggered when eruption heat melts snow and ice or heavy rain mobilizes loose ash. Follows river valleys and can travel tens of kilometers from the volcano.",
  },
  gas: {
    label: "Volcanic gas",
    definition:
      "Invisible plumes of CO₂, SO₂, and H₂S released from vents and cracks. Can pool in low spots and suffocate people and animals, or cause respiratory illness downwind for weeks.",
  },
  tsunami: {
    label: "Tsunami",
    definition:
      "A large wave generated by a flank collapse, caldera collapse into the sea, underwater pyroclastic flow, or a submarine explosion. Can strike coastlines with little warning and thousands of kilometers away.",
  },
  collapse: {
    label: "Edifice collapse",
    definition:
      "A catastrophic landslide of part of the volcano's cone — sometimes cubic kilometers of rock — triggered by magma intrusion, earthquakes, or long-term weakening. Can sweep away everything downslope and trigger tsunamis if it reaches the sea.",
  },
  lava: {
    label: "Lava flows",
    definition:
      "Rivers of molten rock moving downslope. Slow enough to outrun on foot, but unstoppable: everything they reach burns, and they can bury entire neighborhoods for years.",
  },
  ballistic: {
    label: "Ballistic ejecta",
    definition:
      "Rocks, lava bombs, and blocks launched in ballistic arcs from the vent during explosions. Typically dangerous within a few kilometers of the summit. Has no warning once an explosion starts.",
  },
  flood: {
    label: "Volcanic flooding",
    definition:
      "Sudden, massive floods — often called jökulhlaups when ice is involved — when a glacier-capped volcano melts its ice or an eruption breaches a crater lake. Can surge downstream faster than any person or vehicle can outrun.",
  },
};
